help show: user.help_show()
help language: user.help_show("lang")
help apps: user.help_show("apps")
help tags: user.help_show("tags")
help private: user.help_show("private")

help hide: user.help_hide()
help refresh: user.help_refresh()
help next: user.help_next_page()
help last: user.help_previous_page()
help jump <user.number>: user.help_set_page(number - 1)
